# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official
kotlin.native.disableCompilerDownload=false
kotlin.mpp.applyDefaultHierarchyTemplate=false

# KMP
kotlin.mpp.androidSourceSetLayout.version=2

# Compose
android.defaults.buildfeatures.buildconfig=true
